/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/n7OAlVsOPw2
 */
import { Button } from '@/components/ui/button';

export function PfpBuilder() {
	return (
		<div className="flex flex-col h-screen w-full gap-2 items-center justify-center p-4 text-center md:gap-4">
			<div className="grid w-full max-w-sm gap-2">
				<h1 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
					Upload your files
				</h1>
				<p className="text-sm text-gray-500 md:text-base/relaxed dark:text-gray-400">
					Drag and drop your files into the area below or use the button to
					select your files.
				</p>
			</div>
			<div className="flex flex-col gap-2">
				<div className="grid w-full min-[300px] max-w-sm p-4 border-dashed border-2 border-gray-200 rounded-lg border-gray-200/40 dark:border-gray-800/40">
					<PlusIcon className="mx-auto h-6 w-6 text-gray-300 dark:text-gray-700" />
					<p className="mx-auto text-sm text-gray-500 dark:text-gray-400">
						Drag and drop your files here
					</p>
				</div>
				<Button size="lg">Select Files</Button>
			</div>
		</div>
	);
}

function PlusIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
			alt="Plus Icon"
			role="img"
			aria-label="Plus Icon"
		>
			<title>Plus Icon</title>
			<path d="M12 5v14" />
		</svg>
	);
}
